// import React, { useEffect } from 'react';
// import Contex from './Contex';

// const USERADD = () => {

//     const {user}=Contex()
//     useEffect(()=>{

//         const data={
//             email:user.email,
//             name: user.displayName,
//             status:'User',
    
//         }
//         console.log(data)
//     // loader:({params})=>fetch(`https://b9a12-server-side-safwan169.vercel.app/alldata/${params.id}`),
//         axios.post(` https://b9a12-server-side-safwan169.vercel.app/user/${user.email}`, data)
//         .then(res => {
//             console.log('nowdata', res.data);
//             // setUserData(res.data)
//         })
//     })
//     return (
//         <div>
            
//         </div>
//     );
// };

// export default USERADD;